/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author Windows 10
 */
public class Alarma extends javax.swing.JFrame {

    int xMouse,yMouse;
    public Alarma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        AgregarBt = new javax.swing.JPanel();
        AgregarTxt = new javax.swing.JLabel();
        AgregarBt1 = new javax.swing.JPanel();
        AgregarTxt1 = new javax.swing.JLabel();
        nombretitulo = new javax.swing.JLabel();
        separador3 = new javax.swing.JSeparator();
        infoNombre = new javax.swing.JLabel();
        nombretitulo1 = new javax.swing.JLabel();
        Codigotitulo1 = new javax.swing.JLabel();
        separador5 = new javax.swing.JSeparator();
        separador6 = new javax.swing.JSeparator();
        infoNombre1 = new javax.swing.JLabel();
        infoFecha = new javax.swing.JLabel();
        inoUnidades = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 40));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoCir.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 200, 170));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        Titulo.setText("Configuracion de Alarma");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 30));

        AgregarBt.setBackground(new java.awt.Color(0, 134, 190));

        AgregarTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        AgregarTxt.setForeground(new java.awt.Color(255, 255, 255));
        AgregarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarTxt.setText("AGREGAR ALARMA");
        AgregarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AgregarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AgregarBtLayout = new javax.swing.GroupLayout(AgregarBt);
        AgregarBt.setLayout(AgregarBtLayout);
        AgregarBtLayout.setHorizontalGroup(
            AgregarBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarBtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AgregarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AgregarBtLayout.setVerticalGroup(
            AgregarBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarBtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AgregarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(AgregarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 180, 40));

        AgregarBt1.setBackground(new java.awt.Color(0, 134, 190));

        AgregarTxt1.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        AgregarTxt1.setForeground(new java.awt.Color(255, 255, 255));
        AgregarTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarTxt1.setText("VER ALARMAS");
        AgregarTxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AgregarTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarTxt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarTxt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarTxt1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout AgregarBt1Layout = new javax.swing.GroupLayout(AgregarBt1);
        AgregarBt1.setLayout(AgregarBt1Layout);
        AgregarBt1Layout.setHorizontalGroup(
            AgregarBt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarBt1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AgregarTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AgregarBt1Layout.setVerticalGroup(
            AgregarBt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarBt1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AgregarTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(AgregarBt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 180, 40));

        nombretitulo.setText("Nombre:");
        jPanel1.add(nombretitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, 20));

        separador3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, 10));
        jPanel1.add(infoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, -1));

        nombretitulo1.setText("Unidades Minimas:");
        jPanel1.add(nombretitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 20));

        Codigotitulo1.setText("Fecha:");
        jPanel1.add(Codigotitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 50, 20));

        separador5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(separador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 90, 10));

        separador6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(separador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 160, 10));
        jPanel1.add(infoNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, 20));
        jPanel1.add(infoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 160, 20));
        jPanel1.add(inoUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void AgregarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarTxtMouseClicked

    private void AgregarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarTxtMouseEntered

    private void AgregarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTxtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarTxtMouseExited

    private void AgregarTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTxt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarTxt1MouseClicked

    private void AgregarTxt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTxt1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarTxt1MouseEntered

    private void AgregarTxt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTxt1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarTxt1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alarma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarBt;
    private javax.swing.JPanel AgregarBt1;
    private javax.swing.JLabel AgregarTxt;
    private javax.swing.JLabel AgregarTxt1;
    private javax.swing.JLabel Codigotitulo1;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel infoFecha;
    private javax.swing.JLabel infoNombre;
    private javax.swing.JLabel infoNombre1;
    private javax.swing.JLabel inoUnidades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombretitulo;
    private javax.swing.JLabel nombretitulo1;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador5;
    private javax.swing.JSeparator separador6;
    // End of variables declaration//GEN-END:variables
}
