/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inicio;


import java.awt.Color;

/**
 *
 * @author Windows 10
 */
public class InicioLogin extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public InicioLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        bg = new javax.swing.JPanel();
        Modificarbt = new javax.swing.JPanel();
        BuscarBtTxt = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Producto = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        CodigoDelProducto = new javax.swing.JLabel();
        CodigoEntrante = new javax.swing.JTextField();
        nombretitulo = new javax.swing.JLabel();
        Codigotitulo = new javax.swing.JLabel();
        unidadestitulo = new javax.swing.JLabel();
        EliminarBt = new javax.swing.JPanel();
        EliminarTxt = new javax.swing.JLabel();
        PrecioTitulo = new javax.swing.JLabel();
        modificarBt = new javax.swing.JPanel();
        loginBtnTxt4 = new javax.swing.JLabel();
        verImagenBt = new javax.swing.JPanel();
        verImagenTxt = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        separador3 = new javax.swing.JSeparator();
        separador4 = new javax.swing.JSeparator();
        separador5 = new javax.swing.JSeparator();
        infoPrecio = new javax.swing.JLabel();
        infoNombre = new javax.swing.JLabel();
        infoCodigo = new javax.swing.JLabel();
        infoUnidades = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(550, 400));
        bg.setMinimumSize(new java.awt.Dimension(550, 400));
        bg.setPreferredSize(new java.awt.Dimension(540, 420));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Modificarbt.setBackground(new java.awt.Color(0, 134, 190));

        BuscarBtTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        BuscarBtTxt.setForeground(new java.awt.Color(255, 255, 255));
        BuscarBtTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuscarBtTxt.setText("BUSCAR");
        BuscarBtTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BuscarBtTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarBtTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuscarBtTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarBtTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ModificarbtLayout = new javax.swing.GroupLayout(Modificarbt);
        Modificarbt.setLayout(ModificarbtLayout);
        ModificarbtLayout.setHorizontalGroup(
            ModificarbtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarbtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BuscarBtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ModificarbtLayout.setVerticalGroup(
            ModificarbtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarbtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BuscarBtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(Modificarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, 40));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoCir.png"))); // NOI18N
        bg.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 200, 170));

        Producto.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        Producto.setText("Producto");
        bg.add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, 30));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 40));

        separador.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 90, 10));

        CodigoDelProducto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CodigoDelProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        CodigoDelProducto.setText("Codigo del Producto");
        bg.add(CodigoDelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 30));

        CodigoEntrante.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CodigoEntrante.setForeground(new java.awt.Color(204, 204, 204));
        CodigoEntrante.setText("Codigo:");
        CodigoEntrante.setBorder(null);
        CodigoEntrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoEntranteActionPerformed(evt);
            }
        });
        bg.add(CodigoEntrante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 230, 30));

        nombretitulo.setText("Nombre:");
        bg.add(nombretitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 50, 20));

        Codigotitulo.setText("Codigo:");
        bg.add(Codigotitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 50, 20));

        unidadestitulo.setText("Unidades:");
        bg.add(unidadestitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 60, 20));

        EliminarBt.setBackground(new java.awt.Color(0, 134, 190));

        EliminarTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        EliminarTxt.setForeground(new java.awt.Color(255, 255, 255));
        EliminarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarTxt.setText("ELIMINAR");
        EliminarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EliminarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EliminarBtLayout = new javax.swing.GroupLayout(EliminarBt);
        EliminarBt.setLayout(EliminarBtLayout);
        EliminarBtLayout.setHorizontalGroup(
            EliminarBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarBtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EliminarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EliminarBtLayout.setVerticalGroup(
            EliminarBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarBtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EliminarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(EliminarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 130, 40));

        PrecioTitulo.setText("Precio:");
        bg.add(PrecioTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 50, 20));

        modificarBt.setBackground(new java.awt.Color(0, 134, 190));

        loginBtnTxt4.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        loginBtnTxt4.setForeground(new java.awt.Color(255, 255, 255));
        loginBtnTxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtnTxt4.setText("MODIFICAR");
        loginBtnTxt4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginBtnTxt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnTxt4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnTxt4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnTxt4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout modificarBtLayout = new javax.swing.GroupLayout(modificarBt);
        modificarBt.setLayout(modificarBtLayout);
        modificarBtLayout.setHorizontalGroup(
            modificarBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarBtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginBtnTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        modificarBtLayout.setVerticalGroup(
            modificarBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarBtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginBtnTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(modificarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        verImagenTxt.setText("Ver Imagen");

        javax.swing.GroupLayout verImagenBtLayout = new javax.swing.GroupLayout(verImagenBt);
        verImagenBt.setLayout(verImagenBtLayout);
        verImagenBtLayout.setHorizontalGroup(
            verImagenBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verImagenBtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(verImagenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        verImagenBtLayout.setVerticalGroup(
            verImagenBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verImagenBtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(verImagenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(verImagenBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 90, 30));

        separador1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 90, 10));

        separador2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 230, 10));

        separador3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 160, 10));

        separador4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 160, 10));

        separador5.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(separador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 90, 10));

        infoPrecio.setText("ejemplo");
        bg.add(infoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 90, -1));

        infoNombre.setText("ejemplo");
        bg.add(infoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 90, -1));

        infoCodigo.setText("ejemplo");
        bg.add(infoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 90, -1));

        infoUnidades.setText("ejemplo");
        bg.add(infoUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarTxtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarTxtMouseExited

    private void EliminarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarTxtMouseEntered

    private void EliminarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarTxtMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void CodigoEntranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoEntranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoEntranteActionPerformed

    private void BuscarBtTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarBtTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarBtTxtMouseClicked

    private void BuscarBtTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarBtTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarBtTxtMouseEntered

    private void BuscarBtTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarBtTxtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarBtTxtMouseExited

    private void loginBtnTxt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxt4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnTxt4MouseClicked

    private void loginBtnTxt4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxt4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnTxt4MouseEntered

    private void loginBtnTxt4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxt4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnTxt4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarBtTxt;
    private javax.swing.JLabel CodigoDelProducto;
    private javax.swing.JTextField CodigoEntrante;
    private javax.swing.JLabel Codigotitulo;
    private javax.swing.JPanel EliminarBt;
    private javax.swing.JLabel EliminarTxt;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Modificarbt;
    private javax.swing.JLabel PrecioTitulo;
    private javax.swing.JLabel Producto;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel infoCodigo;
    private javax.swing.JLabel infoNombre;
    private javax.swing.JLabel infoPrecio;
    private javax.swing.JLabel infoUnidades;
    private javax.swing.JLabel loginBtnTxt4;
    private javax.swing.JPanel modificarBt;
    private javax.swing.JLabel nombretitulo;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador5;
    private javax.swing.JLabel unidadestitulo;
    private javax.swing.JPanel verImagenBt;
    private javax.swing.JLabel verImagenTxt;
    // End of variables declaration//GEN-END:variables
}
