/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Modelo.Entrada;
import Modelo.Pedido;
import Modelo.Producto;
import Modelo.Salida;
import Proyecto.AccesoriosNauticos;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Betoloti24
 */
public class VerPedidos extends javax.swing.JFrame {

    private List<Pedido> lista_pedido;
    private int indice;
    
    public VerPedidos() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setIconImage((new ImageIcon("src/Imagenes/Mini_Logo.png")).getImage());
        this.setLocationRelativeTo(null); // medio de la pantalla
        this.setResizable(false); //no se puede modificas
        BAtras.setEnabled(false);
        indice = 0;
        lista_pedido = AccesoriosNauticos.getLista_pedidos();          
        actualizarInfo(lista_pedido.get(indice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LIcono = new javax.swing.JLabel();
        LVPedidos = new javax.swing.JLabel();
        LFechaP = new javax.swing.JLabel();
        LCodigo = new javax.swing.JLabel();
        LFechaL = new javax.swing.JLabel();
        TipoPedido = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ICodigo = new javax.swing.JLabel();
        IFechaP = new javax.swing.JLabel();
        ITipoP = new javax.swing.JLabel();
        IFechaL = new javax.swing.JLabel();
        BAtras = new javax.swing.JButton();
        BDelante = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        favicon = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        TGanProvee = new javax.swing.JLabel();
        IGanProvee = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        LIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoCir.png"))); // NOI18N

        LVPedidos.setBackground(new java.awt.Color(102, 102, 102));
        LVPedidos.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LVPedidos.setForeground(new java.awt.Color(153, 153, 153));
        LVPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LVPedidos.setText("Gestionar Pedidos");
        LVPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LVPedidos.setPreferredSize(new java.awt.Dimension(200, 16));

        LFechaP.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        LFechaP.setForeground(new java.awt.Color(153, 153, 153));
        LFechaP.setText("Fecha de Emisión:");

        LCodigo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        LCodigo.setForeground(new java.awt.Color(153, 153, 153));
        LCodigo.setText("Código: ");

        LFechaL.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        LFechaL.setForeground(new java.awt.Color(153, 153, 153));
        LFechaL.setText("Fecha de Recepción:");

        TipoPedido.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TipoPedido.setForeground(new java.awt.Color(153, 153, 153));
        TipoPedido.setText("Tipo de Pedido:");

        jButton1.setBackground(new java.awt.Color(37, 134, 218));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VER PRODUCTOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ICodigo.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        ICodigo.setForeground(new java.awt.Color(153, 153, 153));
        ICodigo.setText(" ");

        IFechaP.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        IFechaP.setForeground(new java.awt.Color(153, 153, 153));
        IFechaP.setText(" ");

        ITipoP.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        ITipoP.setForeground(new java.awt.Color(153, 153, 153));
        ITipoP.setText(" ");

        IFechaL.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        IFechaL.setForeground(new java.awt.Color(153, 153, 153));
        IFechaL.setText(" ");

        BAtras.setBackground(new java.awt.Color(255, 255, 255));
        BAtras.setFont(new java.awt.Font("Roboto", 1, 46)); // NOI18N
        BAtras.setForeground(new java.awt.Color(37, 134, 218));
        BAtras.setText("<");
        BAtras.setBorder(null);
        BAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BAtras.setMaximumSize(new java.awt.Dimension(45, 63));
        BAtras.setMinimumSize(new java.awt.Dimension(45, 63));
        BAtras.setPreferredSize(new java.awt.Dimension(51, 63));
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasActionPerformed(evt);
            }
        });

        BDelante.setBackground(new java.awt.Color(255, 255, 255));
        BDelante.setFont(new java.awt.Font("Roboto", 1, 46)); // NOI18N
        BDelante.setForeground(new java.awt.Color(37, 134, 218));
        BDelante.setText(">");
        BDelante.setBorder(null);
        BDelante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BDelante.setMaximumSize(new java.awt.Dimension(45, 63));
        BDelante.setMinimumSize(new java.awt.Dimension(45, 63));
        BDelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDelanteActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(37, 134, 218));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CREAR ENTRADA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        favicon.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        favicon.setForeground(new java.awt.Color(153, 153, 153));
        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        favicon.setText("Visualización");

        jButton3.setBackground(new java.awt.Color(37, 134, 218));
        jButton3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CREAR SALIDA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TGanProvee.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TGanProvee.setForeground(new java.awt.Color(153, 153, 153));
        TGanProvee.setText("Ganancia:");

        IGanProvee.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        IGanProvee.setForeground(new java.awt.Color(153, 153, 153));
        IGanProvee.setText(" ");

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LFechaL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IFechaL, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LFechaP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IFechaP, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(favicon)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(TipoPedido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ITipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TGanProvee))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(LCodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ICodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IGanProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LVPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(LIcono)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(BAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BDelante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(LVPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(favicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LCodigo)
                                .addComponent(ICodigo))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LFechaP)
                            .addComponent(IFechaP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LFechaL)
                            .addComponent(IFechaL))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoPedido)
                            .addComponent(ITipoP)
                            .addComponent(TGanProvee)
                            .addComponent(IGanProvee)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(LIcono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BDelante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Boton para ver los productos de un pedido
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Actualizamos los datos de la ventana pedidos
        AccesoriosNauticos.getVPedidos().actualizar(lista_pedido.get(indice).getCod(), lista_pedido);
        // Modificamos la visualizacion
        this.setVisible(false);
        AccesoriosNauticos.getVPedidos().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Accion de pulsar el boton de atras
    private void BAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasActionPerformed
        indice--;
        if (indice == 0) BAtras.setEnabled(false);
        BDelante.setEnabled(true);
        actualizarInfo(lista_pedido.get(indice));
    }//GEN-LAST:event_BAtrasActionPerformed

    // Accion de pulsar el boton de adelante
    private void BDelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDelanteActionPerformed
        indice++;
        if (indice+1 == lista_pedido.size()) BDelante.setEnabled(false);
        BAtras.setEnabled(true);
        actualizarInfo(lista_pedido.get(indice));
    }//GEN-LAST:event_BDelanteActionPerformed

    //Accion de crear un pedido
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        AccesoriosNauticos.getVAProd().setTipo(1);
        AccesoriosNauticos.getVCEntrada().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        AccesoriosNauticos.getVAProd().setTipo(2);
        AccesoriosNauticos.getVCSalida().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        AccesoriosNauticos.getVVPedidos().setVisible(false);
        AccesoriosNauticos.getVInventario().setVisible(true);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    // Metodo para actualizar los datos del pedido
    public void actualizarInfo(Pedido ped){
        // Formatear fechas
        // En esta linea de código estamos indicando el nuevo formato que queremos para nuestra fecha.
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        // Aqui usamos la instancia formatter para darle el formato a la fecha. Es importante ver que el resultado es un string.
        String fechaETexto = formatter.format(ped.getFecha_emision());
        Date fecha_re = ped.getFecha_recepcion();
        String fechaRTexto = (fecha_re == null) ? "": formatter.format(fecha_re);
        
        ICodigo.setText("" + ped.getCod());
        IFechaP.setText(fechaETexto);
        IFechaL.setText(fechaRTexto);
        ITipoP.setText((ped instanceof Entrada)? "Entrada": "Salida");
        
        if (ped instanceof Entrada){
            TGanProvee.setText("Proveedor: ");
            Entrada entrada = (Entrada) ped;
            IGanProvee.setText("" + entrada.getProovedor());
        }else{
            TGanProvee.setText("Ganancia: ");
            Salida salida = (Salida) ped;
            IGanProvee.setText("" + salida.getGanancia() + "$");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAtras;
    private javax.swing.JButton BDelante;
    private javax.swing.JLabel ICodigo;
    private javax.swing.JLabel IFechaL;
    private javax.swing.JLabel IFechaP;
    private javax.swing.JLabel IGanProvee;
    private javax.swing.JLabel ITipoP;
    private javax.swing.JLabel LCodigo;
    private javax.swing.JLabel LFechaL;
    private javax.swing.JLabel LFechaP;
    private javax.swing.JLabel LIcono;
    private javax.swing.JLabel LVPedidos;
    private javax.swing.JLabel TGanProvee;
    private javax.swing.JLabel TipoPedido;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel favicon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
